Section "Device"
    Identifier  "FBDEV"
    Driver      "fbdev"
    Option      "fbdev"  "/dev/fb0"
EndSection

Section "Screen"
    Identifier  "Screen0"
    Device      "FBDEV"
    DefaultDepth 16
EndSection
