Section "InputClass"
    Identifier      "QDtech touchscreen"
    MatchProduct    "QDtech MPI5001"
    Driver          "evdev"
    Option          "AccelerationProfile"  "-1"
    Option          "AccelerationScheme"   "none"
    Option          "Emulate3Buttons"      "false"
    Option          "SwapAxes"             "false"
EndSection
